// Code generated by Godin vv0.4.0; DO NOT EDIT.
package subscriber

import (
	godinAMQP "github.com/lukasjarosch/godin/pkg/amqp"
	"github.com/lukasjarosch/godin/pkg/log"
	"github.com/streadway/amqp"
)

func InitUserCreatedSubscriber(channel *amqp.Channel, svc service.Greeter, logger log.Logger) (subscriber godinAMQP.Subscriber, err error) {
	subscription := &godinAMQP.Subscription{
		Exchange: "user-exchange",
		AutoAck:  false,
		Queue: godinAMQP.SubscriptionQueue{
			AutoDelete: false,
			Durable:    true,
			Exclusive:  false,
			Name:       "user-created-queue",
			NoWait:     false,
		},
		Topic: "user.created",
	}
	subscriber = godinAMQP.NewSubscriber(channel, subscription)
	if err = subscriber.Subscribe(UserCreatedSubscriber(logger, svc)); err != nil {
		logger.Error("failed to subscribe to user.created", "err", err)
		return subscriber, err
	}
	logger.Info("subscribed to topic 'user.created'", "topic", subscription.Topic, "queue", subscription.Queue.Name, "exchange", subscription.Exchange)
	return subscriber, nil
}
