apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stringer
    platform: go
    framework: gokit
    generator: godin
    version: godin-stringer-version
  name: stringer
  namespace: godin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stringer
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "3000"
        prometheus.io.path: /metrics
      labels:
        app: stringer
        platform: go
        framework: gokit
        generator: godin
        version: godin-stringer-version
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Zurich
            - name: GRPC_ADDRESS
              value: "0.0.0.0:50051"
            - name: DEBUG_ADDRESS
              value: "0.0.0.0:3000"
            - name: LOG_LEVEL
              value: "info"
          image: registry.hub.docker.com/godin-stringer:godin-stringer-version
          imagePullPolicy: IfNotPresent
          name: stringer
          resources:
          	requests:
          	  cpu: 1m
              memory: 15Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
