apiVersion: v1
kind: Service
metadata:
  name: yyy
  namespace: yyy
spec:
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: http-debug
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: yyy
  sessionAffinity: None
  type: ClusterIP
