apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: godin
spec:
  ports:
    - name: grpc
      port: 50051
      protocol: TCP
      targetPort: 50051
    - name: http-debug
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: hello
  sessionAffinity: None
  type: ClusterIP
