// Code generated by Godin vv0.4.0; DO NOT EDIT.

package endpoint

import (
	"github.com/go-kit/kit/endpoint"

	"github.com/lukasjarosch/godin-examples/greeter/internal/service"
	"github.com/lukasjarosch/godin/pkg/log"
	godinMiddleware "github.com/go-godin/middleware"
)

type Set struct {
	HelloEndpoint endpoint.Endpoint
}

func Endpoints(service service.Greeter, logger log.Logger) Set {

	var hello endpoint.Endpoint
	{
		hello = HelloEndpoint(service)
		hello = godinMiddleware.Prometheus("Hello")(hello)
		hello = godinMiddleware.Logging(logger, "Hello")(hello)
	}

	return Set{
		HelloEndpoint: hello,
	}
}
