// Code generated by Godin v0.4.0; DO NOT EDIT.
package amqp

import (
	"github.com/pkg/errors"
	"github.com/streadway/amqp"

	"github.com/go-godin/log"
	middleware "github.com/go-godin/middleware/amqp"
	"github.com/go-godin/rabbitmq"

	"github.com/lukasjarosch/godin-examples/stringer/internal/service"
	"github.com/lukasjarosch/godin-examples/stringer/internal/service/subscriber"
)

type SubscriberSet struct {
	userCreatedSubscriber rabbitmq.Subscriber

	userUpdatedSubscriber rabbitmq.Subscriber
}

// Subscriptions will initialize all AMQP subscriptions
func Subscriptions(channel *amqp.Channel) SubscriberSet {
	return SubscriberSet{
		userCreatedSubscriber: rabbitmq.NewSubscriber(channel, &rabbitmq.Subscription{
			Exchange: "exchange-name",
			Topic:    "user.created",
			AutoAck:  false,
			Queue: rabbitmq.SubscriptionQueue{
				AutoDelete: false,
				Durable:    true,
				Exclusive:  false,
				Name:       "user-created-queue",
				NoWait:     false,
			},
		}),

		userUpdatedSubscriber: rabbitmq.NewSubscriber(channel, &rabbitmq.Subscription{
			Exchange: "exchange-name",
			Topic:    "user.updated",
			AutoAck:  false,
			Queue: rabbitmq.SubscriptionQueue{
				AutoDelete: false,
				Durable:    true,
				Exclusive:  false,
				Name:       "user-updated-queue",
				NoWait:     false,
			},
		}),
	}
}
func (ss SubscriberSet) UserCreatedSubscriber(logger log.Logger, usecase service.Stringer) error {
	handler := subscriber.UserCreatedSubscriber(logger, usecase)
	handler = middleware.Logging(logger, "user.created", handler)
	handler = middleware.PrometheusInstrumentation("user.created", handler)
	handler = middleware.RequestID(handler)

	if err := ss.userCreatedSubscriber.Subscribe(handler); err != nil {
		logger.Error("failed to subscribe to user.created", "err", err, "transport", "AMQP")
		return errors.Wrap(err, "failed to subscribe to user.created")
	}
	logger.Info(
		"subscribed to topic 'user.created'",
		"topic", ss.userCreatedSubscriber.Subscription.Topic,
		"queue", ss.userCreatedSubscriber.Subscription.Queue.Name,
		"exchange", ss.userCreatedSubscriber.Subscription.Exchange,
		"transport", "AMQP",
	)

	return nil
}

func (ss SubscriberSet) UserUpdatedSubscriber(logger log.Logger, usecase service.Stringer) error {
	handler := subscriber.UserUpdatedSubscriber(logger, usecase)
	handler = middleware.Logging(logger, "user.updated", handler)
	handler = middleware.PrometheusInstrumentation("user.updated", handler)
	handler = middleware.RequestID(handler)

	if err := ss.userUpdatedSubscriber.Subscribe(handler); err != nil {
		logger.Error("failed to subscribe to user.updated", "err", err, "transport", "AMQP")
		return errors.Wrap(err, "failed to subscribe to user.updated")
	}
	logger.Info(
		"subscribed to topic 'user.updated'",
		"topic", ss.userUpdatedSubscriber.Subscription.Topic,
		"queue", ss.userUpdatedSubscriber.Subscription.Queue.Name,
		"exchange", ss.userUpdatedSubscriber.Subscription.Exchange,
		"transport", "AMQP",
	)

	return nil
}

// Shutdown will call Shutdown() on all registered subscriptions
func (ss SubscriberSet) Shutdown() (err error) {
	err = ss.userCreatedSubscriber.Shutdown()

	return err
}
