// Code generated by Godin vv0.4.0; DO NOT EDIT.

package endpoint

import (
	"github.com/go-kit/kit/endpoint"

	"github.com/lukasjarosch/godin-examples/user/internal/service"
	"github.com/lukasjarosch/godin/pkg/log"
	godinMiddleware "github.com/lukasjarosch/godin/pkg/middleware"
)

type Set struct {
	CreateEndpoint endpoint.Endpoint
	GetEndpoint    endpoint.Endpoint
	ListEndpoint   endpoint.Endpoint
	DeleteEndpoint endpoint.Endpoint
}

func Endpoints(service service.User, logger log.Logger) Set {

	var create endpoint.Endpoint
	{
		create = CreateEndpoint(service)
		create = godinMiddleware.Prometheus("Create")(create)
		create = godinMiddleware.Logging(logger, "Create")(create)
	}
	var get endpoint.Endpoint
	{
		get = GetEndpoint(service)
		get = godinMiddleware.Prometheus("Get")(get)
		get = godinMiddleware.Logging(logger, "Get")(get)
	}
	var list endpoint.Endpoint
	{
		list = ListEndpoint(service)
		list = godinMiddleware.Prometheus("List")(list)
		list = godinMiddleware.Logging(logger, "List")(list)
	}
	var delete endpoint.Endpoint
	{
		delete = DeleteEndpoint(service)
		delete = godinMiddleware.Prometheus("Delete")(delete)
		delete = godinMiddleware.Logging(logger, "Delete")(delete)
	}

	return Set{
		CreateEndpoint: create,
		GetEndpoint:    get,
		ListEndpoint:   list,
		DeleteEndpoint: delete,
	}
}
